events/urls.py
from django.urls import include, re_path, path
from .views import *
from . import views


app_name = 'events'

urlpatterns = [
    path('Termine/', index, name='events_index'),
    #EVENT:
    path('Termine/<str:unit>', views.events_show, name='events_show'),
    path('Termine/create/', views.event_create, name='event_create'),
    path('Termine/edit/<int:pk>/', views.event_edit, name="event_edit"),
    path('Termine/delete/<int:pk>/',views.event_delete, name='event_delete'),

    #KINDTABLE:
    path('Kategorie/', views.kind_show, name='kind_show'),
    path('Kategorie/create/', views.kind_create, name='kind_create'),
    path('Kategorie/edit/<int:pk>/', views.kind_edit, name="kind_edit"),
    path('Kategorie/delete/<int:pk>/',views.kind_delete, name='kind_delete'),
    
]

units/urls.py
from django.urls import path
from .views import *
from . import views

app_name = 'units'

urlpatterns = [
    path('Standorte/', index, name='units_index'),
    path('Standorte/<str:unit>', detail, name='unit_detail'),
    #path('Standorte/create',create_unit, name='create_unit'),
   # path('',detail_unit,name="detail_unit"),
]

webapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', TemplateView.as_view(template_name='./general/main.html'), name='home'),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('',include('units.urls')),
    path('',include('profiles.urls')),
    path('',include('events.urls')),
    path('',include('newsletters.urls')),
    path('',include('knowledges.urls')),
    path('',include('documents.urls')),
    path(r'^imagefit/', include('imagefit.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

events/models.py
from django.db import models
from units.models import Unit

class Event(models.Model):
    name = models.CharField(max_length=256)
    description = models.TextField()
    kind = models.ForeignKey(to='Kindtable', on_delete=models.CASCADE, null=True, blank=True)
    unit = models.ForeignKey(to= 'units.Unit',on_delete=models.CASCADE, null=True, blank=True)
    date = models.DateField(null=True, blank=True)
    time =  models.TimeField(auto_now=False, auto_now_add=False, null=True, blank=True)

    def __str__(self):
        return "{0}".format(self.name)
        #return "({0}) {1}".format(self.date,self.name)

class Kindtable(models.Model):
    name = models.CharField(max_length=256)
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return "{0}".format(self.name)

events/forms.py
from django import forms
from .models import Event, Kindtable, Unit
import datetime


class EventForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Termin'}))
    description = forms.CharField(widget=forms.Textarea(attrs={'class':'form-control','placeholder':'Beschreibung'}))
    kind = forms.ModelChoiceField(queryset=Kindtable.objects.all().order_by('name'),widget=forms.Select(attrs={'class':'form-control','placeholder':'Termin'}),label="Kategorie",)
    unit = forms.ModelChoiceField(queryset=Unit.objects.all().order_by('name'),widget=forms.Select(attrs={'class':'form-control','placeholder':'Termin'}),label="Einheit")
    date = forms.DateField(initial=datetime.date.today,widget=forms.SelectDateWidget(attrs={'class':'form-control','placeholder':'Datum'}),)
    time = forms.TimeField(widget=forms.TimeInput(format='%H:%M', attrs={'class':' timepicker form-control','placeholder':'ss:mm'}))

    class Meta:
        model = Event
        fields = ('name', 'description', 'kind', 'unit', 'date', 'time',)


class KindForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Kategorie'}))
    description = forms.CharField(widget=forms.Textarea(attrs={'class':'form-control','placeholder':'Beschreibung'}))

    class Meta:
        model = Kindtable
        fields = ('name','description',)

events/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from .models import *
from datetime import datetime 
from .forms import EventForm, KindForm


def index(request):
    context = {'events':Event.objects.all().order_by('date'),'units':Unit.objects.all(), 'kinds':Kindtable.objects.all()}
    return render(request, template_name="events/event_index.html",context=context)

#EVENT:
def events_show(request, unit):
    if unit == 'Alle':
        unitid = Unit.objects.all()
        context = {'events':Event.objects.filter().order_by('date'), 'units':Unit.objects.all(),}
    else:
        unitid = Unit.objects.get(slug=unit)
        context = {'events':Event.objects.filter(unit=unitid).order_by('date'), 'units':Unit.objects.all()}
    return render(request, template_name="events/event_index.html",context=context)
def event_create(request):
    if request.method == "POST":
        form = EventForm(request.POST)
        if form.is_valid():
            event = form.save(commit=False)
            event.save()
            return redirect(reverse('events:events_index'))
    else:
        form = EventForm()
    context = {'events':Event.objects.all().order_by('date'),'units':Unit.objects.all(), 'kinds':Kindtable.objects.all(),'form':form, 'titel':'Termin erstellen'}
    return render(request, 'events/event_form.html', context=context )
def event_edit(request, pk):
    event = get_object_or_404(Event, pk=pk)
    context = {'events':Event.objects.all().order_by('date'),'units':Unit.objects.all()}
    if request.method == "POST":
        form = EventForm(request.POST, instance=event)
        if form.is_valid():
            event = form.save(commit=False)
            event.save()
            return redirect(reverse('events:events_index'))
    else:
        form = EventForm(instance=event)
    context = {'events':Event.objects.all().order_by('date'),'units':Unit.objects.all(), 'kinds':Kindtable.objects.all(),'form':form, 'titel':'Termin bearbeiten'}
    return render(request, 'events/event_form.html', context=context )
def event_delete(request,pk):
    try:
        Event.objects.get(pk=pk).delete()
    
    finally:
        return redirect(reverse('events:events_index'))

#KINDTABLE
def kind_show(request):
    context = {'kinds':Kindtable.objects.all(), 'units':Unit.objects.all(),}
    return render(request, template_name="events/kind_index.html",context=context)
def kind_create(request):
    if request.method == "POST":
        form = KindForm(request.POST)
        if form.is_valid():
            kind = form.save(commit=False)
            kind.save()
            print("create")
            return redirect(reverse('events:kind_show'))
    else:
        form = KindForm()
    context = {'units':Unit.objects.all(), 'kinds':Kindtable.objects.all(),'form':form, 'titel':'Kategorie bearbeiten'}
    return render(request, 'events/kind_form.html', context=context )
def kind_edit(request, pk):
    event = get_object_or_404(Kindtable, pk=pk)
    if request.method == "POST":
        form = KindForm(request.POST, instance=event)
        if form.is_valid():
            kind = form.save(commit=False)
            kind.save()
            return redirect(reverse('events:kind_show'))
        else:
            print("not valid")
    else:
        form = KindForm(instance=event)
    context = {'units':Unit.objects.all(), 'form':form, 'titel':'Kategorie bearbeiten'}
    return render(request, 'events/kind_form.html', context=context )
def kind_delete(request,pk):
    try:
        Kindtable.objects.get(pk=pk).delete()
    finally:
        return redirect(reverse('events:kind_show'))

events/templates/events/event_form.html
{% extends 'general/main.html' %}
{% load static %}
{% block sidebar %}
    {% include 'events/sidebar.html' %}
{% endblock%}
{% block content%}
<div class="row card-deck">
  <div class="col">
    <form method="POST" class="event-form">{% csrf_token %}
      <div class="card text-center" style="width: 30rem;">
          <div class="card-header">
            {{titel}}
          </div>
          <div class="card-body">
            <div class="input-group input-group-sm mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text" id="inputGroup-sizing-sm">Termin</span>
              </div>
              {{form.name}}
          </div>
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">Beschreibung</span>
              </div>
              {{ form.description}}
            </div>
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <label class="input-group-text" for="inputGroupSelect01">Art des Termins</label>
              </div>
              {{form.kind}}
            </div>
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <label class="input-group-text" for="inputGroupSelect01">Einheit</label>
              </div>
              {{form.unit}}
            </div>
            <div class="input-group input-group-sm mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text" id="inputGroup-sizing-sm">Datum</span>
              </div>
              {{form.date}}
            </div>
            <div class="input-group input-group-sm mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text" id="inputGroup-sizing-sm">Uhrzeit</span>
              </div>
              {{form.time}}
            </div>
          </div>
          <div class="card-footer text-muted">
            <div class="login-div-button">
              <input type="submit" value="Hinzufügen" name="save" id="save" class="btn btn-success login-button"/>
            </div>
          </div>
        </div>
    </form>
  </div>
</div>

{% endblock %}

events/templates/events/event_index.html
{% extends 'general/main.html' %}
{% load static %}
{% block sidebar %}
    {% include 'events/sidebar.html' %}
{% endblock%}
{% block content%}
  <div class="container-fluid">
    <div class="card-columns">
        {% for event in events %}
            <div class="card text-center">
                <div class="card-header">
                    <div class="row">
                        {% if user.is_authenticated and request.user.is_superuser%}
                            <div class="col-2"><a href="{% url 'events:event_edit' pk=event.pk %}"><img src="{% static 'icons/edit.svg' %}"></a></div>
                        {% endif %}
                        <div class="col">{{event.date}}, {{event.time}}</div>
                        {% if user.is_authenticated and request.user.is_superuser%}
                            <div class="col-2"><a href="{% url 'events:event_delete' pk=event.pk %}"><img src="{% static 'icons/delete.svg' %}"></a></div>
                        {% endif %}
                    </div>
                </div>
                <div class="card-body">
                    <h5 class="card-title">{{event.name}} ({{event.kind}})</h5>
                    <p class="card-text">{{event.description}}</p>
                </div>
                <div class="card-footer">
                    {% if event.unit.slug == 'Stadt' %}
                    <a class="btn btn-light" href="{% url 'units:units_index'%}">
                        Alle Einheiten
                    </a>
                {% else %}
                    <a class="btn btn-light" href="{% url 'units:unit_detail' unit=event.unit %}">
                        Einheit: {{event.unit}}
                    </a>
                {% endif %}
                </div>

            </div>
        {% endfor %}
    </div>
  </div>
{% endblock %}

events/templates/events/kind_form.html
{% extends 'general/main.html' %}
{% load static %}
{% block sidebar %}
    {% include 'events/sidebar.html' %}
{% endblock%}
{% block content%}
    <form method="POST" class="event-form">{% csrf_token %}
      <div class="card text-center" style="width: 30rem;">
        <div class="card-header">
          {{titel}}
        </div>
        <div class="card-body">
          <div class="input-group input-group-sm mb-3">
            <div class="input-group-prepend">
              <span class="input-group-text" id="inputGroup-sizing-sm">Kategorie</span>
            </div>
            {{form.name}}
          </div>
          <div class="input-group mb-3">
            <div class="input-group-prepend">
              <span class="input-group-text">Beschreibung</span>
            </div>
            {{ form.description}}
          </div>
      </div>
      <div class="card-footer text-muted">
          <input type="submit" value="Hinzufügen" name="save" id="save" class="btn btn-success login-button"/>
      </div>
    </form>    
{% endblock %}

events/templates/events/kind_index.html
{% extends 'general/main.html' %}
{% load static %}
{% block sidebar %}
    {% include 'events/sidebar.html' %}
{% endblock%}
{% block content%}
  <div class="container-fluid">
    <div class="card-columns">
        {% for kind in kinds %}
            <div class="card text-center">
                <div class="card-header">
                    <div class="row">
                        {% if user.is_authenticated and request.user.is_superuser%}
                            <div class="col-2"><a href="{% url 'events:kind_edit' pk=kind.pk %}"><img src="{% static 'icons/edit.svg' %}"></a></div>
                        {% endif %}
                        <div class="col">{{kind.name}}</div>
                        {% if user.is_authenticated and request.user.is_superuser%}
                            <div class="col-2"><a href="{% url 'events:kind_delete' pk=kind.pk %}"><img src="{% static 'icons/delete.svg' %}"></a></div>
                        {% endif %}
                    </div>
                </div>
                <div class="card-body">
                    <p class="card-text">{{kind.description}}</p>
                </div>
            </div>
        {% endfor %}
    </div>
  </div>
{% endblock %}

events/templates/events/sidebar.html
{% load static %}
<div class="card text-left">
    <div class="card-header text-center">
      Termine
    </div>
    <div class="nav flex-column nav-pills text-left"aria-orientation="vertical">
        <a class="nav-link btn btn-light text-left"  href="{% url 'events:events_show' unit='Alle' %}">Alle Termine</a>
        {% for unit in units %}
            {% if unit.slug == 'Stadt' %}
                <a class="nav-link btn btn-light text-left" href="{% url 'events:events_show' unit=unit.slug %}">{{unit.name}}</a>
            {% else %}
                <a class="nav-link btn btn-light text-left" href="{% url 'events:events_show' unit=unit.slug %}">Einheit {{unit.slug}}</a>
            {% endif %}
        {% endfor %}
    </div>
    {% if user.is_authenticated and request.user.is_superuser%}
        <div class="card-footer nav flex-column nav-pills">
            <a class="nav-link btn btn-light"  title="Erstelle einen neuen Termin"  href="{% url 'events:event_create' %}">
                <img src="{% static 'icons/add.svg' %}">
                <img src="{% static 'icons/event-note.svg' %}">
            </a>
        </div>
        <div class="card-footer nav justify-content-center nav-pills">
            <a class="nav-link btn btn-light" title="Erstelle eine neue Kategorie" href="{% url 'events:kind_create' %}">
                <img src="{% static 'icons/library_add.svg' %}">
            </a>
            <a class="nav-link btn btn-light" title="Erstelle eine neue Kategorie" href="{% url 'events:kind_show' %}">
                <img src="{% static 'icons/library_books.svg' %}">
            </a>
        </div>
    {% endif %}
</div>