newsletters/urls.py
from django.urls import path
from .views import *
from . import views

app_name = 'newsletters'

urlpatterns = [
    path('News/', index, name='news_index'),
    #News
    path('News/<str:topic>', views.news_show, name='news_show'),
    path('News/create/', views.news_create, name='news_create'),
    path('News/edit/<int:pk>/', views.news_edit, name='news_edit'),
    path('News/delete/<int:pk>/',views.news_delete, name='news_delete'),
    #Topic
    path('Themen/', views.topic_show, name='topic_show'),
    path('Themen/create/', views.topic_create, name='topic_create'),
    path('Themen/edit/<int:pk>/', views.topic_edit, name="topic_edit"),
    path('Themen/delete/<int:pk>/',views.topic_delete, name='topic_delete'),
]

units/urls.py
from django.urls import path
from .views import *
from . import views

app_name = 'units'

urlpatterns = [
    path('Standorte/', index, name='units_index'),
    path('Standorte/<str:unit>', detail, name='unit_detail'),
    #path('Standorte/create',create_unit, name='create_unit'),
   # path('',detail_unit,name="detail_unit"),
]

webapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', TemplateView.as_view(template_name='./general/main.html'), name='home'),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('',include('units.urls')),
    path('',include('profiles.urls')),
    path('',include('events.urls')),
    path('',include('newsletters.urls')),
    path('',include('knowledges.urls')),
    path('',include('documents.urls')),
    path(r'^imagefit/', include('imagefit.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

newsletters/models.py
from django.db import models
from profiles.models import Profile

class News(models.Model):
    name = models.CharField(max_length=256)
    topic = models.ForeignKey(to='Topic', on_delete=models.CASCADE, null=True, blank=True)
    image = models.ImageField(upload_to='news_images' ,null=True, blank=True)
    message = models.TextField()
    published = models.DateField(null=True, blank=True)
    created_by = models.ForeignKey(to= 'profiles.Profile',on_delete=models.DO_NOTHING, null=True, blank=True)

    def __str__(self):
        return self.name

class Topic(models.Model):
    name = models.CharField(max_length=256,null=True, blank=True)
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.name

newsletters/forms.py
from django import forms
from .models import Topic, News
from profiles.models import Profile
import datetime


class NewsForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Titel'}))
    message = forms.CharField(widget=forms.Textarea(attrs={'class':'form-control','placeholder':'Nachricht'}))
    topic = forms.ModelChoiceField(queryset=Topic.objects.all().order_by('name'),widget=forms.Select(attrs={'class':'form-control','placeholder':'Thema'}))
    published = forms.DateField(initial=datetime.date.today,widget=forms.SelectDateWidget(attrs={'class':'form-control','placeholder':'Datum'}))
    created_by = forms.ModelChoiceField(queryset=Profile.objects.all(),widget=forms.Select(attrs={'class':'form-control','placeholder':'Ersteller'}))

    class Meta:
        model = News
        fields = ('name', 'message', 'topic', 'published', 'created_by')


class TopicForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Thema'}))
    description = forms.CharField(widget=forms.Textarea(attrs={'class':'form-control','placeholder':'Beschreibung'}))

    class Meta:
        model = Topic
        fields = ('name','description',)

newsletters/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from .models import *
from .forms import NewsForm, TopicForm
from webapp.utils import *

def index(request):
    c_user = check_admin(request.user)
    context = {'newsletters':News.objects.all(), 'topics': Topic.objects.all(),'c_user':c_user}
    return render(request, template_name="newsletters/news_index.html", context=context)

#news:
def news_show(request, topic):
    c_user = check_admin(request.user)
    if topic == 'Alle':
        context = {'newsletters':News.objects.filter().order_by('published'), 'topics':Topic.objects.all(),'c_user':c_user}
    else:
        topicid = Topic.objects.get(name=topic)
        context = {'newsletters':News.objects.filter(topic=topicid).order_by('published'), 'topics':Topic.objects.all(),'c_user':c_user}
    return render(request, template_name="newsletters/news_index.html",context=context)
def news_create(request):
    c_user = check_admin(request.user)
    context = {'newsletters':News.objects.all(), 'topics': Topic.objects.all(),'message':'Nachricht erstellen','c_user':c_user}
    if request.method == "POST":
        form = NewsForm(request.POST)
        if form.is_valid():
            news = form.save(commit=False)
            news.save()
            return redirect(reverse('newsletters:news_index'))
    else:
        form = NewsForm()
    context = {'newsletters':News.objects.all(), 'topics': Topic.objects.all(),'form':form,'message':'Nachricht erstellen','c_user':c_user}
    return render(request, 'newsletters/news_form.html', context=context )
def news_edit(request, pk):
    c_user = check_admin(request.user)
    news = get_object_or_404(News, pk=pk)
    context = {'news':News.objects.all().order_by('published'),'topics':Topic.objects.all(),'c_user':c_user}
    if request.method == "POST":
        form = NewsForm(request.POST, instance=news)
        if form.is_valid():
            news = form.save(commit=False)
            news.save()
            return redirect(reverse('newsletters:news_index'))
        else:
            print("not valid")
    else:
        form = NewsForm(instance=news)
    context = {'news':News.objects.all().order_by('published'),'topics':Topic.objects.all(),'form':form, 'titel':'Nachricht bearbeiten','c_user':c_user}
    return render(request, 'newsletters/news_form.html', context=context )
def news_delete(request,pk):
    try:
        News.objects.get(pk=pk).delete()
    finally:
        return redirect(reverse('newsletters:news_index'))

#topic
def topic_show(request):
    c_user = check_admin(request.user)
    context = {'topics':Topic.objects.all(),'c_user':c_user}
    return render(request, template_name="newsletters/topic_index.html",context=context)
def topic_create(request):
    c_user = check_admin(request.user)
    if request.method == "POST":
        form = TopicForm(request.POST)
        if form.is_valid():
            topic = form.save(commit=False)
            topic.save()
            return redirect(reverse('newsletters:topic_show'))
    else:
        form = TopicForm()
    context = {'topics':Topic.objects.all(),'form':form, 'titel':'Thema bearbeiten','c_user':c_user}
    return render(request, 'newsletters/topic_form.html', context=context )
def topic_edit(request, pk):
    c_user = check_admin(request.user)
    news = get_object_or_404(Topic, pk=pk)
    if request.method == "POST":
        form = TopicForm(request.POST, instance=news)
        if form.is_valid():
            topic = form.save(commit=False)
            topic.save()
            return redirect(reverse('newsletters:topic_show'))
        else:
            print("not valid")
    else:
        form = TopicForm(instance=news)
    context = {'topics':Topic.objects.all(), 'form':form, 'titel':'Kategorie bearbeiten','c_user':c_user}
    return render(request, 'newsletters/topic_form.html', context=context )
def topic_delete(request,pk):
    try:
        Topic.objects.get(pk=pk).delete()
    
    finally:
        return redirect(reverse('newsletters:topic_show'))

newsletters/templates/newsletters/news_form.html
{% extends 'general/main.html' %}
{% load static %}
{% block sidebar %}
    {% include 'newsletters/sidebar.html' %}
{% endblock%}
{% block content%}
<div class="row card-deck">
  <div class="col">
    <form method="POST" class="event-form">{% csrf_token %}
      <div class="card text-center" style="width: 30rem;">
          <div class="card-header">
            {{titel}}
          </div>
          <div class="card-body">
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text" id="inputGroup-sizing-sm">Titel</span>
              </div>
              {{form.name}}
          </div>
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">Topic</span>
              </div>
              {{ form.topic}}
            </div>
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <label class="input-group-text" for="inputGroupSelect01">Nachricht</label>
              </div>
              {{form.message}}
            </div>
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <label class="input-group-text" for="inputGroupSelect01">Veröffentlicht</label>
              </div>
              {{form.published}}
            </div>
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text" id="inputGroup-sizing-sm">Ersteller</span>
              </div>
              {{form.created_by}}
            </div>
          </div>
          <div class="card-footer text-muted">
            <div class="login-div-button">
              <input type="submit" value="Hinzufügen" name="save" id="save" class="btn btn-success login-button"/>
            </div>
          </div>
        </div>
    </form>
  </div>
</div>

{% endblock %}

newsletters/templates/newsletters/news_index.html
{% extends 'general/main.html' %}
{% load static %}
{% load imagefit %}
{% block sidebar %}
    {% include 'newsletters/sidebar.html' %}
{% endblock%}
{% block content%}
  <div class="container-fluid ">
    <div class="col-sm-10 pl-0">
        {% for newsletter in newsletters %}
        <div class="pb-3">
          <div class="card text-center">
            <div class="card-header">
              <div class="row">
                {% if user.is_authenticated and c_user == True%}
                    <div class="col-2"><a href="{% url 'newsletters:news_edit' pk=newsletter.pk %}"><img src="{% static 'icons/edit.svg' %}"></a></div>
                {% endif %}
                <div class="col">{{newsletter.topic}}</div>
                {% if user.is_authenticated and c_user == True%}
                    <div class="col-2"><a href="{% url 'newsletters:news_delete' pk=newsletter.pk %}"><img src="{% static 'icons/delete.svg' %}"></a></div>
                {% endif %}
              </div>
            </div>
            <div class="card-body">
              <h5 class="card-title">{{newsletter.name}}</h5>
              <p class="card-text">{{newsletter.message}}</p>
            </div>
            <div class="card-footer text-muted">
              Erstellt von {{newsletter.created_by}} | {{newsletter.published}}.
            </div>
          </div>
        </div>

        {% endfor %}
    </div>
  </div>
{% endblock %}

newsletters/templates/newsletters/sidebar.html
{% load static %}
<div class="card text-left">
    <div class="card-header text-center">
      Themen
    </div>
    <div class="nav flex-column nav-pills text-left"aria-orientation="vertical">
        <a class="nav-link btn btn-light text-left"  href="{% url 'newsletters:news_show' topic='Alle' %}">Alle Nachrichten</a>
        {% for topic in topics %}
            <a class="nav-link btn btn-light text-left" title="{{ topic.description }}" href="{% url 'newsletters:news_show' topic=topic.name %}">{{ topic.name }}</a>
        {% endfor %}
    </div>
    {% if user.is_authenticated and c_user == True %}
        <div class="card-footer nav justify-content-center nav-pills">
            <a class="nav-link btn btn-light" title="Erstelle eine neue Nachricht" href="{% url 'newsletters:news_create' %}">
                <img src="{% static 'icons/add.svg' %}">
                <img src="{% static 'icons/add_comment.svg' %}">
            </a>
            

        </div>
        <div class="card-footer nav justify-content-center nav-pills">
            <a class="nav-link btn btn-light" title="Erstelle ein neues Thema" href="{% url 'newsletters:topic_create' %}">
                <img src="{% static 'icons/library_add.svg' %}">
            </a>
            <a class="nav-link btn btn-light" title="Siehe dir alle Themen an" href="{% url 'newsletters:topic_show' %}">
                <img src="{% static 'icons/library_books.svg' %}">
            </a>
        </div>
    {% endif %}
</div>

newsletters/templates/newsletters/topic_form.html
{% extends 'general/main.html' %}
{% load static %}
{% block sidebar %}
    {% include 'newsletters/sidebar.html' %}
{% endblock%}
{% block content%}
<div class="row card-deck">
  <div class="col">
    <form method="POST" class="event-form">{% csrf_token %}
      <div class="card text-center" style="width: 30rem;">
          <div class="card-header">
            {{titel}}
          </div>
          <div class="card-body">
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text" id="inputGroup-sizing-sm">Name</span>
              </div>
              {{form.name}}
          </div>
          <div class="input-group mb-3">
            <div class="input-group-prepend">
              <span class="input-group-text">Beschreibung</span>
            </div>
            {{ form.description}}
          </div>
        </div>
        <div class="card-footer text-muted">
          <input type="submit" value="Hinzufügen" name="save" id="save" class="btn btn-success login-button"/>
      </div>
    </form>
  </div>
</div>

{% endblock %}

newsletters/templates/newsletters/topic_index.html
{% extends 'general/main.html' %}
{% load static %}
{% block sidebar %}
    {% include 'newsletters/sidebar.html' %}
{% endblock%}
{% block content%}
  <div class="container-fluid ">
    <div class="col-sm-10 pl-0">
        {% for topic in topics %}
        <div class="pb-3">
          <div class="card text-center">
            <div class="card-header">
              <div class="row">
                {% if user.is_authenticated and request.user.is_superuser%}
                    <div class="col-2"><a href="{% url 'newsletters:topic_edit' pk=topic.pk %}"><img src="{% static 'icons/edit.svg' %}"></a></div>
                {% endif %}
                <div class="col">{{topic.name}}</div>
                {% if user.is_authenticated and request.user.is_superuser%}
                    <div class="col-2"><a href="{% url 'newsletters:topic_delete' pk=topic.pk %}"><img src="{% static 'icons/delete.svg' %}"></a></div>
                {% endif %}
            </div>
            </div>
            <div class="card-body">
              <p class="card-text">{{topic.description}}</p>
            </div>
          </div>
        </div>

        {% endfor %}
    </div>
  </div>
{% endblock %}