newsletters/urls.py
from django.urls import path
from .views import *
from . import views

app_name = 'newsletters'

urlpatterns = [
    path('News/', index, name='news_index'),
    #News
    path('News/<str:topic>', views.news_show, name='news_show'),
    path('News/create/', views.news_create, name='news_create'),
    path('News/edit/<int:pk>/', views.news_edit, name='news_edit'),
    path('News/delete/<int:pk>/',views.news_delete, name='news_delete'),
    #Topic
    path('Themen/', views.topic_show, name='topic_show'),
    path('Themen/create/', views.topic_create, name='topic_create'),
    path('Themen/edit/<int:pk>/', views.topic_edit, name="topic_edit"),
    path('Themen/delete/<int:pk>/',views.topic_delete, name='topic_delete'),
]

profiles/urls.py
from django.urls import include, re_path, path
from .views import *
from . import views


app_name = 'profiles'

urlpatterns = [
    path('Profil/', index, name='index'),
    path('Profil/<str:user>',detail ,name='detail_profil'),
]

units/urls.py
from django.urls import path
from .views import *
from . import views

app_name = 'units'

urlpatterns = [
    path('Standorte/', index, name='units_index'),
    path('Standorte/<str:unit>', detail, name='unit_detail'),
    #path('Standorte/create',create_unit, name='create_unit'),
   # path('',detail_unit,name="detail_unit"),
]

webapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', TemplateView.as_view(template_name='./general/main.html'), name='home'),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('',include('units.urls')),
    path('',include('profiles.urls')),
    path('',include('events.urls')),
    path('',include('newsletters.urls')),
    path('',include('knowledges.urls')),
    path('',include('documents.urls')),
    path(r'^imagefit/', include('imagefit.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

units/models.py
from django.db import models


class Unit(models.Model):
    slug = models.CharField(max_length=20, null=True, blank=True)
    image = models.ImageField(upload_to='images' ,null=True, blank=True)
    wallpaper = models.CharField(max_length=256, null=True, blank=True)
    name = models.CharField(max_length=256)
    street = models.CharField(max_length=256)
    housenumber = models.CharField(max_length=256)
    postcode = models.CharField(max_length=256)
    place = models.CharField(max_length=256)
    website = models.CharField(max_length=256, null=True, blank=True)

    def __str__(self):
        return '{0}'.format(self.slug)

class Workinghour(models.Model):
    WOCHENTAGE = (
        ('Mo','Montag'),
        ('Di','Dienstag'),
        ('Mi','Mittwoch'),
        ('Do','Donnerstag'),
        ('Fr','Freitag'),
        ('Sa','Samstag'),
        ('SO','Sonntag'),
    )
    unit = models.ForeignKey('Unit',on_delete=models.CASCADE, null=True, blank=True)
    group = models.ForeignKey('profiles.group',on_delete=models.CASCADE, null=True, blank=True)
    day = models.CharField(max_length=15, null=True, blank=True, choices=WOCHENTAGE)
    starttime =  models.TimeField(auto_now=False, auto_now_add=False, null=True, blank=True)
    endtime = models.TimeField(auto_now=False, auto_now_add=False, null=True, blank=True)

    def __str__(self):
        return '{0} ({1})'.format(self.unit, self.group)

units/forms.py
from django import forms
from .models import Unit

class UnitCreateForm(forms.ModelForm):
    class Meta:
        model= Unit
        fields= ('slug', 'name', 'street', 'housenumber', 'postcode', 'place',)

units/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from .models import *
from datetime import datetime 
from .forms import UnitCreateForm
from webapp.utils import *



def index(request):
    a_user = check_admin(request.user)
    e_user = check_einheitsfueher(request.user)
    user_permissions = {'a_user':a_user, 'e_user':e_user}

    context = {'nav_units':Unit.objects.exclude(slug="Stadt"),'user_permissions':user_permissions}
    return render(request, template_name="units/unit_index.html",context=context)

def detail(request, unit):
    a_user = check_admin(request.user)
    e_user = check_einheitsfueher(request.user)
    user_permissions = {'a_user':a_user, 'e_user':e_user}

    nav_units = Unit.objects.exclude(slug="Stadt")
    unit = Unit.objects.get(slug=unit)
    leaderships = Profile.objects.all().filter(unit=unit.id,role=ROLE_EINHEITSFUEHRUNG)
    young_leaderships = Profile.objects.all().filter(unit=unit.id,role=ROLE_JUGENDWART)

    
    amount_active = Profile.objects.all().filter(unit=unit.id,group=GROUP_AKTIVE).count() #Aktive
    amount_young = Profile.objects.all().filter(unit=unit.id,group=GROUP_JUGEND).count() #Jugendfeuerwehr
    amount_counselors = Profile.objects.all().filter(unit=unit.id,role=ROLE_BETREUERTEAM).count() #Betreuer
    amount_honor = Profile.objects.all().filter(unit=unit.id,group=GROUP_ALTERABTEILUNG).count() #Alters und Ehrenabteilung
    amounts = {"amount_active":amount_active, "amount_young":amount_young,"amount_honor":amount_honor,"amount_counselors":amount_counselors}

    context = {'nav_units':nav_units,'unit':unit,'young_leaderships':young_leaderships,'leaderships':leaderships,'user_permissions':user_permissions,'amounts':amounts}
    return render(request, template_name="units/unit_detail.html",context=context)
    

units/templates/units/add.html
<form method="POST" action="{% url 'units:create_unit' %}">
    {% csrf_token %}
    <div class="input-group mt-2">
        <div class="input-group-prepend">
            <span class="input-group-text" style="width: 10rem;">Einheit:</span>
        </div>
            <input type="text" class="form-control" id="slug" name="slug" placeholder="Einheitsname">
    </div>
    <div class="input-group mt-2">
        <div class="input-group-prepend">
            <span class="input-group-text" style="width: 10rem;">Vollständiger Name:</span>
        </div>
        <input type="text" class="form-control" id="name" name="name" placeholder="Freiwilige Feuerwehr Löschzug/Löschgruppe Einheit">
    </div>
    <div class="input-group mt-2">
        <div class="input-group-prepend">
            <span class="input-group-text" style="width: 10rem;">Straße:</span>
        </div>
        <input type="text" class="form-control" id="street" name="street" placeholder="Straße">
    </div>
    <div class="input-group mt-2">
        <div class="input-group-prepend">
            <span class="input-group-text" style="width: 10rem;">Hausnummer:</span>
        </div>
        <input type="text" class="form-control" id="housenumber" name="housenumber" placeholder="Hausnummer">
    </div>
    <div class="input-group mt-2">
        <div class="input-group-prepend">
            <span class="input-group-text" style="width: 10rem;">PLZ:</span>
        </div>
        <input type="text" class="form-control" id="postcode" name="postcode" placeholder="PLZ">
    </div>
    <div class="input-group mt-2">
        <div class="input-group-prepend">
            <span class="input-group-text" style="width: 10rem;">Ort:</span>
        </div>
        <input type="text" class="form-control" id="place" name="place" placeholder="Ort">
    </div>
    <div class="input-group mt-2">
      <div class="input-group-prepend">
        <label class="input-group-text" for="inputGroupSelect01" style="width: 10rem;">Übungsdiensttag</label>
      </div>
      <select class="custom-select" id="inputGroupSelect01" type="text" name="day">
        <option selected>Wähle aus...</option>
        <option value="Montag">Montag</option>
        <option value="Dienstag">Dienstag</option>
        <option value="Mittwoch">Mittwoch</option>
        <option value="Donnerstag">Donnerstag</option>
        <option value="Freitag">Freitag</option>
        <option value="Samstag">Samstag</option>
        <option value="Sonntag">Sonntag</option>
      </select>
    </div>
    <div class="input-group mt-2">
        <div class="input-group-prepend">
            <span class="input-group-text" style="width: 10rem;">Startzeit:</span>
        </div>
        <input class="form-control" id="starttime" name="starttime" placeholder="SS:MM" type="time"/>
    </div>
    <div class="input-group mt-2">
        <div class="input-group-prepend">
            <span class="input-group-text" style="width: 10rem;">Endzeit:</span>
        </div>
        <input class="form-control" id="endtime" name="endtime" placeholder="SS:MM" type="time"/>
    </div>

    <div class="login-div-button text-center mt-2">
    <input type="submit" value="Speichern" name="save" id="save" class="btn btn-success login-button"></input>
    </div>
</form>

units/templates/units/sidebar.html
{% load static %}
<div class="card text-left">
    <div class="card-header text-center">
      Standorte / Einheiten
    </div>
    <div class="nav flex-column nav-pills text-left"aria-orientation="vertical">
        <a class="nav-link btn btn-light text-left"  href="{% url 'units:units_index' %}">Alle Standorte/Einheiten</a>
        {% for nav_unit in nav_units %}
            <a class="nav-link btn btn-light text-left" title="{{ nav_unit.name }}" href="{% url 'units:unit_detail' unit=nav_unit.slug %}">{{ nav_unit.slug }}</a>
        {% endfor %}
    </div>
    {% if user.is_authenticated and user_permissions.e_user == True %}
        IN PROGRESS
        <div class="card-footer nav justify-content-center nav-pills">
            <a class="nav-link btn btn-light" title="Erstelle eine neue Nachricht" href="{% url 'newsletters:news_create' %}">
                <img src="{% static 'icons/add.svg' %}">
                <img src="{% static 'icons/add_comment.svg' %}">
            </a>
            

        </div>
        <div class="card-footer nav justify-content-center nav-pills">
            <a class="nav-link btn btn-light" title="Erstelle ein neues Thema" href="{% url 'newsletters:topic_create' %}">
                <img src="{% static 'icons/library_add.svg' %}">
            </a>
            <a class="nav-link btn btn-light" title="Siehe dir alle Themen an" href="{% url 'newsletters:topic_show' %}">
                <img src="{% static 'icons/library_books.svg' %}">
            </a>
        </div>
    {% endif %}
</div>

units/templates/units/unit_detail.html
{% extends 'general/main.html' %}
{% load static %}
{% load imagefit %}
{% block sidebar %}
    {% include 'units/sidebar.html' %}
{% endblock%}
{% block content%}
<div class="card text-left" style="width: auto; height: auto; margin-right: 5px;">
    <div class="card-header">
      {% if unit.image %}
        <img src="{{ unit.image.url }}" class="card-img-top" alt="{{ unit.slug }}" >
      {% endif %}
    </div>

        <div class="accordion" id="accordionExample">
          <div class="card">
            <div class="card-header" id="headingZero">
              <h2 class="mb-0">
                <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapseZero" aria-expanded="false" aria-controls="collapseZero">
                  Standort
                </button>
              </h2>
            </div>
            <div id="collapseZero" class="collapse" aria-labelledby="headingZero" data-parent="#accordionExample">
              <div class="card-body">
                <ul class="list-unstyled">
                  <li>{{ unit.name }}</li>
                  <li>{{ unit.street}} {{ unit.housenumber}}</li>
                  <li>{{ unit.postcode }} {{ unit.place }}</li>
                </ul>
              </div>
            </div>
          </div>
            <div class="card">
              <div class="card-header" id="headingOne">
                <h2 class="mb-0">
                  <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
                    Einheitsführung
                  </button>
                </h2>
              </div>
              <div id="collapseOne" class="collapse" aria-labelledby="headingOne" data-parent="#accordionExample">
                <div class="card-body">
                  <div class="row">
                    {% for leadership in leaderships %}
                      <div class="col">
                        <div class="card w-75">
                          <h5 class="card-header">
                            <a href="{% url 'profiles:detail_profil' user=leadership.username %}" class="nav-link">
                              {{leadership.username}}
                            </a>
                          </h5>
                          {% if leadership.image %}
                            <div class="text-center card">
                              <img src="{{ leadership.image.url }}" class="figure-img img-fluid rounded" style="width: 70%; vertical-align: center;" alt="images.{{leadership.username}}">
                            </div>
                          {% endif %}
                          <div class="card-body">
                            <h6 class="card-title">{{leadership.lastname}}, {{leadership.firstname}}</h6>
                            <p class="card-text text-muted">
                              <ul class="list-unstyled">
                                <li>Einheit: {{leadership.unit}}</li>
                                <li>Geburtstag: {{leadership.birthday}}</li>
                                <li>Email: {{leadership.email}}</li>
                                <li>Handynummer: {{leadership.mobile}}</li>
                              </ul>
                            </p>
                          </div>
                        </div>   
                      </div>  
                    {% endfor %}
                  </div>
                </div>
              </div>
            </div>
            <div class="card">
              <div class="card-header" id="headingTwo">
                <h2 class="mb-0">
                  <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                    Jugendwarte
                  </button>
                </h2>
              </div>
              <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionExample">
                <div class="card-body">
                  <div class="row">
                    {% for young_leadership in young_leaderships %}
                      <div class="col">
                        <div class="card w-75">
                          <h5 class="card-header">
                            <a href="{% url 'profiles:detail_profil' user=young_leadership.username %}" class="nav-link">
                              {{young_leadership.username}}
                            </a>
                          </h5>
                          {% if young_leadership.image %}
                            <div class="text-center card">
                              <img src="{{ young_leadership.image.url }}" class="figure-img img-fluid rounded" style="width: 70%; vertical-align: center;" alt="images.{{young_leadership.username}}">
                            </div>
                          {% endif %}
                          <div class="card-body">
                            <h6 class="card-title">{{young_leadership.lastname}}, {{young_leadership.firstname}}</h6>
                            <p class="card-text text-muted">
                              <ul class="list-unstyled">
                                <li>Einheit: {{young_leadership.unit}}</li>
                                <li>Geburtstag: {{young_leadership.birthday}}</li>
                                <li>Email: {{young_leadership.email}}</li>
                                <li>Handynummer: {{young_leadership.mobile}}</li>
                              </ul>
                            </p>
                          </div>
                        </div>   
                      </div>  
                    {% endfor %}
                  </div>
                </div>
              </div>
            </div>
            <div class="card">
              <div class="card-header" id="headingThree">
                <h2 class="mb-0">
                  <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                    Mitgliederzahlen
                  </button>
                </h2>
              </div>
              <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordionExample">
                <div class="card-body">
                  <table class="table">
                    <thead>
                      <tr>
                        <th scope="col">Abteilung</th>
                        <th scope="col">Mitgleiderzahl</th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        <th scope="row">Aktive Wehr</th>
                        <td>{{ amounts.amount_active }}</td>
                      </tr>
                      <tr>
                        <th scope="row">Jugendfeuerwehr</th>
                        <td>{{ amounts.amount_young }}</td>
                      </tr>
                      <tr>
                        <th scope="row">Betreuerteam</th>
                        <td>{{ amounts.amount_counselors }}</td>
                      </tr>
                      <tr>
                        <th scope="row">Alter und Ehrenabteilung</th>
                        <td>{{ amounts.amount_honor }}</td>
                      </tr>
                    </tbody>
                  </table>
                </div>
              </div>
              <div class="card">
                <div class="card-header" id="headingFour">
                  <h2 class="mb-0">
                    <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
                      Dienstzeiten
                    </button>
                  </h2>
                </div>
                <div id="collapseFour" class="collapse" aria-labelledby="headingFour" data-parent="#accordionExample">
                  <div class="card-body">
                    Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
                  </div>
                </div>

            </div>
          </div>

    <div class="card-footer text-muted">
        Sie finden uns auch unter folgendem Link:
        <a href="https:{{unit.website}}">{{unit.website}}</a>
    </div>
</div>
{% endblock %}

units/templates/units/unit_index.html
{% extends 'general/main.html' %}
{% load static %}
{% load imagefit %}
{% block sidebar %}
    {% include 'units/sidebar.html' %}
{% endblock%}
{% block content%}
<div class="card-columns">
  {% for nav_unit in nav_units %}
  <div class="card text-left" style="width: auto; height: auto;">
      <div class="card-header">
        <div class="row">
          <div class="col-10 my-auto">
            <h4>Einheit: {{nav_unit.slug}}</h4>
          </div>
          <div class="col-2 nav justify-content-center">
            <a class="nav-link btn btn-light" href="{% url 'units:unit_detail' nav_unit.slug %}">
              <img src="{% static 'icons/show.svg' %}">
            </a>
          </div>
        </div>
      
      </div>
      <div class="card-body">
          <h5 class="card-title">Adresse:</h5>
          <ul class="list-unstyled">
              <li>{{nav_unit.name}}</li>
              <li>{{nav_unit.street}} {{nav_unit.housenumber}}</li>
              <li>{{nav_unit.postcode}} {{nav_unit.place}}</li>
          </ul>
      </div>
      <div class="card-footer text-muted">
          <h5 class="card-title">Übungsdienstzeiten:</h5>
          <ul class="list-unstyled">
              <li>Tag: {{nav_unit.day}}</li>
              <li>Beginn: {{nav_unit.starttime}}</li>
              <li>Ende: {{nav_unit.endtime}}</li>
          </ul>
      </div>
  </div>
  {% endfor %}
</div>

  <div class="container-fluid ">
    <div class="col-sm-10 pl-0">
        {% for newsletter in newsletters %}
        <div class="pb-3">
          <div class="card text-center">
            <div class="card-header">
              <div class="row">
                {#% if user.is_authenticated and e_user == True%}
                    <!--<div class="col-2"><a href="{% url 'newsletters:news_edit' pk=newsletter.pk %}"><img src="{% static 'icons/edit.svg' %}"></a></div>-->
                {#% endif %}
                <div class="col">{{newsletter.topic}}</div>
                {#% if user.is_authenticated and e_user == True%}
                    <!--<div class="col-2"><a href="{% url 'newsletters:news_delete' pk=newsletter.pk %}"><img src="{% static 'icons/delete.svg' %}"></a></div>-->
                {#% endif %}
              </div>
            </div>
            <div class="card-body">
              <h5 class="card-title">{{newsletter.name}}</h5>
              <p class="card-text">{{newsletter.message}}</p>
            </div>
            <div class="card-footer text-muted">
              Erstellt von {{newsletter.created_by}} | {{newsletter.published}}.
            </div>
          </div>
        </div>
        {% endfor %}
    </div>
  </div>
{% endblock %}