documents/urls.py
from django.urls import path
from .views import *

app_name = 'documents'

urlpatterns = [
    path('Dokumentvorlagen',index, name='documents_index'),
    path('Dokumentvorlagen/<str:name>',detail, name='document_detail'),
    path('Dokumentvorlagen/create/document',document_create, name='document_create'),
    path('Dokumentvorlagen/edit/<int:pk>/',document_edit, name='document_edit'),
    path('Dokumentvorlagen/delete/<int:pk>/',delete, name='document_delete'),
    path('Dokumentvorlagen/download/<int:id>/',document_download, name='document_download')
]

events/urls.py
from django.urls import include, re_path, path
from .views import *
from . import views


app_name = 'events'

urlpatterns = [
    path('Termine/', index, name='events_index'),
    #EVENT:
    path('Termine/<str:unit>', views.events_show, name='events_show'),
    path('Termine/create/', views.event_create, name='event_create'),
    path('Termine/edit/<int:pk>/', views.event_edit, name="event_edit"),
    path('Termine/delete/<int:pk>/',views.event_delete, name='event_delete'),

    #KINDTABLE:
    path('Kategorie/', views.kind_show, name='kind_show'),
    path('Kategorie/create/', views.kind_create, name='kind_create'),
    path('Kategorie/edit/<int:pk>/', views.kind_edit, name="kind_edit"),
    path('Kategorie/delete/<int:pk>/',views.kind_delete, name='kind_delete'),
    
]

units/urls.py
from django.urls import path
from .views import *
from . import views

app_name = 'units'

urlpatterns = [
    path('Standorte/', index, name='units_index'),
    path('Standorte/<str:unit>', detail, name='unit_detail'),
    #path('Standorte/create',create_unit, name='create_unit'),
   # path('',detail_unit,name="detail_unit"),
]

webapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', TemplateView.as_view(template_name='./general/main.html'), name='home'),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('',include('units.urls')),
    path('',include('profiles.urls')),
    path('',include('events.urls')),
    path('',include('newsletters.urls')),
    path('',include('knowledges.urls')),
    path('',include('documents.urls')),
    path(r'^imagefit/', include('imagefit.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

documents/models.py
from django.db import models

class Filedocument(models.Model):
    name = models.CharField(max_length=256, unique=True)
    description = models.TextField(null=True, blank=True)
    document = models.FileField(upload_to="files/")
    owner = models.ForeignKey(to= 'users.CustomUser',on_delete=models.DO_NOTHING, null=True, blank=True)
    published = models.DateField(null=True, blank=True, auto_now_add=True, editable=False)
    updated = models.DateField(null=True, blank=True)
    

    def __str__(self):
        return "{0} ({1})".format(self.name, self.owner) 

class Commentary(models.Model):
    filedocument = models.ForeignKey(to='Filedocument', on_delete=models.CASCADE, null=True, blank=True)
    owner = models.ForeignKey(to= 'profiles.Profile',on_delete=models.DO_NOTHING, null=True, blank=True)
    comment = models.TextField()
    published = models.DateTimeField(null=True, blank=True, auto_now=True, editable=False)
    

    def __str__(self):
        return "{0} | {1}: {2}".format(self.filedocument, self.owner, self.comment) 

documents/forms.py
from django import forms
from .models import Filedocument, Commentary

class FiledocumentForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Name'}))
    description = forms.CharField(widget=forms.Textarea(attrs={'class':'form-control','placeholder':'Beschreibung'}))
    document = forms.FileField()
   
    class Meta:
        model = Filedocument
        fields = ('name', 'description', 'document',)

class CommentaryForm(forms.ModelForm):
    comment = forms.CharField(widget=forms.Textarea(attrs={'class':'form-control','placeholder':'Beschreibung'}))
    
    class Meta:
        model = Commentary
        fields = ('comment',)

documents/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from .models import *
from webapp.utils import *
from django.http import Http404  
import os
from django.http import FileResponse
from django.utils.text import slugify
from .forms import FiledocumentForm, CommentaryForm

def index(request):
    documents = Filedocument.objects.all()
    c_admin = check_admin(request.user)
    
    context = {'documents':documents, 'c_admin':c_admin}
    return render(request, template_name="documents/index.html",context=context)

def detail(request, name):
    documents = Filedocument.objects.all()
    docfile = Filedocument.objects.get(name=name)
    c_admin = check_admin(request.user)
    comments = Commentary.objects.filter(filedocument=docfile.id)
    context = {'docfile':docfile,'documents':documents, 'c_admin':c_admin,'comments':comments}
    return render(request, template_name="documents/detail.html",context=context)

def document_create(request):
    documents = Filedocument.objects.all()
    c_admin = check_admin(request.user)

    if request.method == "POST":
        form = FiledocumentForm(request.POST, request.FILES)
        if form.is_valid():
            document = form.save(commit=False)
            document.owner = request.user
            document.save()
            return redirect(reverse('documents:documents_index'))
    else:
        form = FiledocumentForm()
    context = {'documents':documents, 'c_admin':c_admin,'form':form, 'titel':'Dokument hochladen'}
    return render(request, 'documents/file_form.html', context=context )

def document_edit(request, pk):
    doc = get_object_or_404(Filedocument, pk=pk)
    documents = Filedocument.objects.all()
    c_admin = check_admin(request.user)

    if request.method == "POST":
        form = FiledocumentForm(request.POST, request.FILES, instance=doc)
        if form.is_valid():
            document = form.save(commit=False)
            document.owner = request.user
            document.save()
            return redirect(reverse('documents:documents_index'))
    else:
        form = FiledocumentForm(instance=doc)
    context = {'documents':documents, 'c_admin':c_admin,'form':form, 'titel':'Dokument hochladen'}
    return render(request, 'documents/file_form.html', context=context )

def delete(request,pk):
    try:
        filedoc = Filedocument.objects.get(pk=pk)
        if filedoc.owner.id == request.user.id or check_admin(request.user) == True:
            filedoc.delete()
    finally:
        return redirect(reverse('documents:documents_index'))

def document_download(request, id):
    item = get_object_or_404(Filedocument, pk=id)
    file_name, file_extension = 	 os.path.splitext(item.document.file.name)
    file_extension = file_extension[1:] # removes dot
    response = FileResponse(item.document.file, 
        content_type = "file/%s" % file_extension)
    response["Content-Disposition"] = "attachment;"\
        "filename=%s.%s" %(slugify(item.name)[:100], file_extension)
    return response

documents/templates/documents/detail.html
{% extends 'general/main.html' %}
{% load static %}
{% load imagefit %}
{% block sidebar %}
    {% include 'documents/sidebar.html' %}
{% endblock%}
{% block content%}

<div class="card text-center">
    <div class="card-header">
        <div class="row">
            {% if request.user.is_authenticated and request.user.id == docfile.owner.id or c_admin == True%}
                <div class="col-2"><a href="{% url 'documents:document_edit' pk=docfile.pk %}"><img src="{% static 'icons/edit.svg' %}"></a></div>
                <div class="col">{{docfile.name}}</div>
                <div class="col-2"><a href="{% url 'documents:document_delete' pk=docfile.pk %}"><img src="{% static 'icons/delete.svg' %}"></a></div>
            {% else %}
                <div class="col">{{docfile.name}}</div>
            {% endif %}
        </div>
    </div>
    <div class="card-body">
        <p class="card-text">{{docfile.description}}</p>
        <a class="btn" title="Download" href="{% url 'documents:document_download' id=docfile.pk %}">
            <img src="{% static 'icons/download.svg' %}">
        </a>   

    </div>
    <div class="card-footer text-muted">
        {% for comment in comments %}
            <div class="card">

                <div class="card-body">
                <blockquote class="blockquote mb-0">
                    <p>{{comment.comment}}</p>
                    <footer class="blockquote-footer">{{comment.owner}} ({{comment.published}})</footer>
                </blockquote>
                </div>
            </div>
        {% endfor %}
    </div>
  </div>




{% endblock %}

documents/templates/documents/file_form.html
{% extends 'general/main.html' %}
{% load static %}
{% load imagefit %}
{% block sidebar %}
    {% include 'documents/sidebar.html' %}
{% endblock%}

{% block content%}
<div class="row card-deck">
  <div class="col">
    <form method="POST" class="event-form" enctype="multipart/form-data">{% csrf_token %}
      <div class="card text-center" style="width: 30rem;">
          <div class="card-header">
            {{titel}}
          </div>
          <div class="card-body">
            <div class="input-group input-group-sm mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text" id="inputGroup-sizing-sm">Termin</span>
              </div>
              {{form.name}}
          </div>
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">Beschreibung</span>
              </div>
              {{ form.description}}
            </div>
            
            <div class="input-group mb-3">
              <div class="input-group-prepend">
              </div>
              {{form.document}}
            </div>
            </div>
          <div class="card-footer text-muted">
            <div class="login-div-button">
              <input type="submit" value="Hinzufügen" name="save" id="save" class="btn btn-success login-button"/>
            </div>
          </div>
        </div>
    </form>
  </div>
</div>

{% endblock %}

documents/templates/documents/index.html
{% extends 'general/main.html' %}
{% load static %}
{% load imagefit %}
{% block sidebar %}
    {% include 'documents/sidebar.html' %}
{% endblock%}
{% block content%}
<div>
        <table class="table table-striped table-bordered table-sm card-header">
            <thead>
                <tr>
                    <th class="text-center" scope="col">Name</th>
                    <th class="text-center" scope="col">Ersteller</th>
                    <th class="text-center" scope="col">Letztes Datum</th>
                    <th class="text-center" scope="col">Ansehen</th>
                    <th class="text-center" scope="col">Download</th>
                </tr>
            </thead>
            <tbody>
                {% for document in documents %}
                    <tr>
                        <td class="align-middle">{{document.name}}</td>
                        <td class="align-middle">{{document.owner}}</td>
                        <td class="align-middle">{{document.published}}</td>
                        <td class="align-middle text-center">
                            <a  class="btn" title="Anschauen" href="{% url 'documents:document_detail' name=document.name %}">
                                <img src="{% static 'icons/show.svg' %}">
                            </a>                           
                        </td>
                        <td class="align-middle text-center">            
                            <a class="btn" title="Download" href="{% url 'documents:document_download' id=document.pk %}">
                                <img src="{% static 'icons/download.svg' %}">
                            </a>      
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
</div>
{% endblock %}

documents/templates/documents/sidebar.html
{% load static %}
<div class="card text-left">
    <div class="card-header text-center">
      Dokumente / Vorlagen
    </div>
    {% if user.is_authenticated or c_admin == True%}
        <div class="card-footer nav flex-column nav-pills">
            <a class="nav-link btn btn-light"  title="Lade eine neue Datei hoch"  href="{% url 'documents:document_create' %}">
                <img src="{% static 'icons/upload.svg' %}">
            </a>
        </div>
        <div class="card-footer nav justify-content-center nav-pills">
            <a class="nav-link btn btn-light" title="Erstelle eine neue Kategorie" href="{% url 'events:kind_create' %}">
                <img src="{% static 'icons/library_add.svg' %}">
            </a>
            <a class="nav-link btn btn-light" title="Erstelle eine neue Kategorie" href="{% url 'events:kind_show' %}">
                <img src="{% static 'icons/library_books.svg' %}">
            </a>
        </div>
    {% endif %}
</div>